#!/usr/bin/env bash
set -e

#========================================================================
# Rebuild Spack Environments
#========================================================================
function git_branch {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/\1/p'
}

#------------------------------------------------------------------------
# save existing spack directory state
#------------------------------------------------------------------------
cd $SPACK_ROOT
branch=$(git_branch)

if [[ "$branch" != "develop" ]]; then
    if git diff; then
        stashed=0
        git stash
    else
        stashed=1
    fi

    git switch develop
fi

#------------------------------------------------------------------------
# update spack
#------------------------------------------------------------------------
git fetch upstream

current_branch=$(git -C ~/src/spack/spack rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" == "develop" ]]; then
    git pull --rebase
fi

#------------------------------------------------------------------------
# update spack builtin repo
#------------------------------------------------------------------------
spack repo update

#------------------------------------------------------------------------
# reconcretize default as the base env
#------------------------------------------------------------------------
spack mark -i $(spack -e default find -H)
spack -e default concretize -f --fresh-roots
spack -e default install
spack gc -by

#------------------------------------------------------------------------
# recompile emacs for compatibility
#------------------------------------------------------------------------
emacs --batch --load ~/.emacs.d/init.el --execute '(kill-emacs)'
emacs --batch --load ~/.emacs.d/init.el --execute '(package-recompile-all)'

#------------------------------------------------------------------------
# reconcretize project environments
#------------------------------------------------------------------------
for env in $(spack env ls | grep -v default); do
    spack -e $env concretize -f --fresh-roots
    spack -e $env install
done

#------------------------------------------------------------------------
# garbage collect all unused specs
#------------------------------------------------------------------------
spack gc -Eby

#------------------------------------------------------------------------
# restore spack working directory state
#------------------------------------------------------------------------
if [[ "$branch" != "develop" ]]; then
    git switch "$branch"
    if $stashed; then
        git stash apply
    fi
fi
